alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias cls='clear'
alias clsh='truncate -s 0 $HISTFILE && reset'
alias ip='ip -c'
alias grep='grep --color=auto'
alias egrep='grep -E --color=auto'
alias fgrep='fgrep -F --color=auto'
alias mkdir='mkdir -p'
alias http='http --style lovelace'
alias ipt='iptables'
alias iptlist='iptables -L -n --line-numbers'
alias ip6t='ip6tables'
alias ip6tlist='ip6tables -L -n --line-numbers'
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'
