[window]
dimensions = { columns = 190, lines = 48 }
dynamic_title = false
title = "BTWOS"
opacity = 0.95

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
size = 10.7

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[colors.normal]
black   = "#181818"
red     = "#ac4242"
green   = "#90a959"
yellow  = "#f4bf75"
blue    = "#6a9fb5"
magenta = "#aa759f"
cyan    = "#75b5aa"
white   = "#d8d8d8"

[colors.bright]
black   = "#6b6b6b"
red     = "#c55555"
green   = "#aac474"
yellow  = "#feca88"
blue    = "#82b8c8"
magenta = "#c28cb8"
cyan    = "#93d3c3"
white   = "#f8f8f8"

[colors.dim]
black   = "#0f0f0f"
red     = "#712b2b"
green   = "#5f6f3a"
yellow  = "#a17e4d"
blue    = "#456877"
magenta = "#704d68"
cyan    = "#4d7770"
white   = "#8e8e8e"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]
