[window]
dimensions = { columns = 150, lines = 37 }
dynamic_title = false
title = "BTWOS"
opacity = 0.93

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
size = 11.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]