[profiles/default]
allow-bold=true
background-darkness=0.80
background-type='transparent'
bold-color='#EDEDEDEDEDED'
copy-selection=true
cursor-shape='ibeam'
default-show-menubar=true
default-size-columns=140
default-size-rows=42
font='FreeMono Bold 12'
foreground-color='#EDEDEDEDEDED'
scroll-on-output=true
scrollback-unlimited=true
silent-bell=true
title='MateTerminal'
title-mode='ignore'
use-custom-default-size=true
use-system-font=false
use-urls=false
visible-name='По умолчанию'
